### ISSUE TITLE
Add the ability to "time" events to show how time is being spent 

### ISSUE THREAD

**Issue by proffalken** [heedy/connectordb-android#4]
The ability to start/stop a timer and have the details recorded to a stream would be great for time/task tracking

**Comment by dkumor** [comment]
Could you expand on that idea a bit please? Can you give me an example of how this would work?

**Comment by proffalken** [comment]
Sure, so I'm thinking about an integrated time tracker where I type what I'm doing and click "start" do the task and click "stop", and it logs something like 

1300hrs - started watching cat videos on YouTube 
1315hrs - stopped watching cat videos on YouTube 
1400hrs - meeting at work
1600hrs - meeting finished 

This would allow for tracking of tasks and give the ability to plot heart rate against task undertaken or time spent in meetings vs productive work done

Not sure if that makes it clearer or not?

**Comment by proffalken** [comment]
Something like https://toggl.com/best-free-time-tracking-app-for-android with connectordb sync

**Comment by dkumor** [comment]
I was planning on adding an ML-based calendar for the 0.4 release of ConnectorDB, but I'll see if this type of event tracker can be implemented directly as a stream in 0.3.

Given the stuff that still needs to be done for 0.3.0, I'll put this onto the list for 0.3.1

**Comment by dkumor** [comment]
As a side note, the new app UI is functional in git right now. If you have experience with react native, or are interested in trying it out, it would be really helpful if you could create a mockup of the UI for this tracking as another tab in the new UI. UI code is in the `src` directory

If you're not a fan of android dev (or just busy), a drawing of what the ideal ui for this would look like would also be useful!

**Comment by proffalken** [comment]
No worries, and there's no rush, I'm just logging these ideas as Ihave them otherwise I'll forget! :) 


Sent from my Samsung device

-------- Original message --------

**Comment by proffalken** [comment]
OK, so I'm not a UI/UX guy, but this is broadly the kind of thing I was thinking.

The "Name" Field becomes the name of the stream and can be selected from a dropdown or typed directly in, timings with the same name are added to the same stream.

Much like the manual input, the name must be lowercase, but there is a description for something more "human readable".

I'd suggest that the JSON schema for timers is something like the following:

```json
{
    'event_name': '<STRING>',
    'event_start_datetime': '<DATETIME>',
    'event_stop_datetime': '<DATETIME>',
    'event_start_location': {
        'latitude': '<FLOAT>',
        'longitude': '<FLOAT>'
    },
    'event_stop_location': {
        'latitude': '<FLOAT>',
        'longitude': '<FLOAT>'
    }
}
```

Obviously if you already have a native lat/long format then use that instead of the FLOAT! :)

![connectordb io timer ui - page 1](https://cloud.githubusercontent.com/assets/262545/23157147/ce6ee8ec-f811-11e6-90f1-c8df65183c5e.png)

**Comment by dkumor** [comment]
Thanks! The data probably wouldn't contain GPS coordinates, since those are already gathered by your phone, and so are redundant (you can even see a map of where you were in the connectordb interface). Other than that, it looks like a very reasonable proposal. I'll look into the details of what it would take to implement something like this for 0.3.1.

**Comment by proffalken** [comment]
Makes sense, I'm all for de-duplication of data! :D

Thanks :)
